### ISSUE TITLE
[Testing]Two update records will be send on reassigning new table for a visit 

### ISSUE THREAD

**Issue by Fatimarouqa** [ro-test/QETest#4]
Two update records will be send on reassigning new table for a visit 
Two update records will be send on reassigning new table for a visit 
Two update records will be send on reassigning new table for a visit 
Two update records will be send on reassigning new table for a visit 
...Two update records will be send on reassigning new table for a visit .....Two update records will be send on reassigning new table for a visit .....Two update records will be send on reassigning new table for a visit ...Two update records will be send on reassigning new table for a visit ...Two update records will be send on reassigning new table for a visit ...Two update records will be send on reassigning new table for a visit .

**Comment by ehabinl** [comment]
ma 7abaito :(
